name: Bug Report
description: Report a bug in PDF.js
title: "[Bug]: "
body:
  - type: textarea
    attributes:
      label: Attach (recommended) or Link to PDF file
    validations:
      required: true

  - type: markdown
    attributes: { value: "---" }

  - type: input
    attributes:
      label: Web browser and its version
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system and its version
    validations:
      required: true
  - type: input
    attributes:
      label: PDF.js version
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Is the bug present in the latest PDF.js version?
      options: ["Yes", "No"]
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Is a browser extension
      options: ["Yes", "No"]
      default: 1
    validations:
      required: true

  - type: markdown
    attributes: { value: "---" }

  - type: textarea
    attributes:
      label: Steps to reproduce the problem
      placeholder: "1.\n2."
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: Also add a screenshot
    validations:
      required: true

  - type: textarea
    attributes:
      label: What went wrong?
      description: Also add a screenshot
    validations:
      required: true

  - type: input
    attributes:
      label: Link to a viewer
      description: Needed if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension

  - type: textarea
    attributes:
      label: Additional context
      description: Do you have anything to add that doesn't fit in the issue template?
